CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR,
    login VARCHAR,
    name VARCHAR,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS MPAs (
     id BIGINT PRIMARY KEY,
     name VARCHAR
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    description VARCHAR,
    release_date DATE,
    duration INTEGER,
    MPA_id BIGINT REFERENCES MPAs(id)
);

CREATE TABLE IF NOT EXISTS friends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    second_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genres (
    id BIGINT PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE IF NOT EXISTS film_genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
    genre_id BIGINT REFERENCES genres(id)
);

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR,
    is_positive BOOLEAN,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
    useful INTEGER
);

CREATE TABLE IF NOT EXISTS reviews_ratings (
    review_id BIGINT REFERENCES reviews(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    status BOOLEAN --true: like; false: dislike
);

CREATE TABLE IF NOT EXISTS events (
                        event_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        timestamp    BIGINT NOT NULL,
                        user_id      BIGINT REFERENCES users(id),
                        event_type   VARCHAR(10) NOT NULL,
                        operation    VARCHAR(10) NOT NULL,
                        entity_id    BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_events_user_timestamp
    ON events(user_id, timestamp DESC);